# Generated by Django 5.0.6 on 2024-07-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('request_count', models.IntegerField(default=0)),
                ('last_request_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ipaddress_log',
                'ordering': ('id',),
            },
        ),
    ]
