# Generated by Django 5.0.6 on 2024-12-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='save_image',
            new_name='save_image_ru',
        ),
        migrations.AddField(
            model_name='marks',
            name='price_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='price_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='save_image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
