# Generated by Django 5.0.6 on 2024-12-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_rename_save_image_marks_save_image_ru_marks_price_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='years',
            field=models.BigIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
