# Generated by Django 5.0.6 on 2024-12-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0003_alter_marks_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('faq_id', models.ManyToManyField(blank=True, null=True, to='db_models.faq')),
            ],
            options={
                'db_table': 'category-faq',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='category-fa_id_042755_idx')],
            },
        ),
    ]
