# Generated by Django 5.0.6 on 2024-12-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0005_alter_marks_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfaq',
            name='faq_id',
            field=models.ManyToManyField(blank=True, to='db_models.faq'),
        ),
    ]
