# Generated by Django 5.0.6 on 2024-12-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_postaloffice_apartment_alter_postaloffice_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('geolocation', models.CharField(blank=True, max_length=300, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fullindex',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='fullindex_id_5b14b3_idx')],
            },
        ),
    ]
