# Generated by Django 5.0.6 on 2024-12-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_fullindex_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullindex',
            name='geolocation',
            field=models.URLField(blank=True, null=True),
        ),
    ]
