# Generated by Django 5.0.6 on 2024-12-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_fullindex_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaloffice',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postaloffice',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
